import javax.swing.JOptionPane;

/**
 *
 * @author jlarr
 */
public class TragaMonedas extends javax.swing.JFrame {

    /**
     * Creates new form TragaMonedas
     */
    public TragaMonedas() {
        initComponents();
        setLocationRelativeTo(null);
        a = new Progreso(Ranura1.getSize());        
        Ranura1.add(a);
        Ranura1.repaint();   
        b = new Progreso(Ranura2.getSize());        
        Ranura2.add(b);
        Ranura2.repaint(); 
        c = new Progreso(Ranura3.getSize());        
        Ranura3.add(c);
        Ranura3.repaint();   
        d = new Progreso(Ranura4.getSize());        
        Ranura4.add(d);
        Ranura4.repaint(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ranura1 = new javax.swing.JLabel();
        Ranura2 = new javax.swing.JLabel();
        Ranura3 = new javax.swing.JLabel();
        Ranura4 = new javax.swing.JLabel();
        girar = new javax.swing.JButton();
        premio = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ranura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono1.JPG"))); // NOI18N
        jPanel1.add(Ranura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 184, 160, 135));

        Ranura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono2.JPG"))); // NOI18N
        jPanel1.add(Ranura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 140, 140));

        Ranura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono3.JPG"))); // NOI18N
        jPanel1.add(Ranura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 150, 150));

        Ranura4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono4.JPG"))); // NOI18N
        jPanel1.add(Ranura4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 180, 140));

        girar.setBackground(new java.awt.Color(51, 153, 255));
        girar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        girar.setForeground(new java.awt.Color(255, 255, 255));
        girar.setText("Buena Suerte!");
        girar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girarActionPerformed(evt);
            }
        });
        jPanel1.add(girar, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 383, 246, 52));

        premio.setEditable(false);
        premio.setBackground(new java.awt.Color(102, 51, 255));
        premio.setBorder(null);
        premio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premioActionPerformed(evt);
            }
        });
        jPanel1.add(premio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 0));

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/titulo.png"))); // NOI18N
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 848, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girarActionPerformed
        // TODO add your handling code here:
        if (girar.getText().equals("Buena Suerte!")){
            girar.setText("PARAR");
            a.startAnimation(); d.startAnimation(); b.startAnimation(); c.startAnimation();
            premio.setText("");
        }
        else
        {
            a.stopAnimation(); b.stopAnimation(); c.stopAnimation(); d.stopAnimation();
            
            if (a.getIm() == b.getIm() && b.getIm() == c.getIm() && c.getIm() == d.getIm()){
                JOptionPane.showMessageDialog(null, "Ganastge el Premio Gordo!!");
            }else{
                JOptionPane.showMessageDialog(null, "Ups, perdiste :(");
            }
           
            
            
            girar.setText("Buena Suerte!");
    }//GEN-LAST:event_girarActionPerformed
    }
    private void premioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_premioActionPerformed

    /**
     * @param args the command line arguments
     */
    Progreso a ; 
    Progreso b ;
    Progreso c ; 
    Progreso d ;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TragaMonedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ranura1;
    private javax.swing.JLabel Ranura2;
    private javax.swing.JLabel Ranura3;
    private javax.swing.JLabel Ranura4;
    private javax.swing.JButton girar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField premio;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
